# Generated by Django 4.2.16 on 2024-10-19 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_periodo', models.IntegerField(blank=True, default=0, null=True)),
                ('creditos_a_cumprir', models.IntegerField(blank=True, default=0, null=True)),
                ('curso', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_avaliacao', models.CharField(blank=True, max_length=200, null=True)),
                ('data_avaliacao', models.DateField(blank=True, null=True)),
                ('hora_avaliacao', models.TimeField(blank=True, null=True)),
                ('sala_avaliacao', models.CharField(blank=True, max_length=200, null=True)),
                ('predio_avaliacao', models.CharField(blank=True, max_length=200, null=True)),
                ('peso_avaliacao', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_disciplina', models.CharField(blank=True, max_length=200, null=True)),
                ('nome_disciplina', models.CharField(blank=True, max_length=200, null=True)),
                ('departamento', models.CharField(blank=True, max_length=200, null=True)),
                ('criterio', models.IntegerField(default=0)),
                ('criterio_formula', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordenador', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.CharField(blank=True, max_length=200, null=True)),
                ('matricula', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('telefone', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_de_usuario', models.CharField(choices=[('Aluno', 'Aluno'), ('Professor', 'Professor')], max_length=200)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_turma', models.CharField(blank=True, max_length=30, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fim', models.TimeField(blank=True, null=True)),
                ('dias_semana', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira')], max_length=33, null=True)),
                ('disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siuni_site.disciplina')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siuni_site.professor')),
            ],
        ),
        migrations.AddField(
            model_name='professor',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professor', to='siuni_site.usuario'),
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=4)),
                ('aluno', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siuni_site.aluno')),
                ('avaliacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siuni_site.avaliacao')),
            ],
        ),
        migrations.CreateModel(
            name='MediaFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g1', models.DecimalField(decimal_places=1, max_digits=3)),
                ('g2', models.DecimalField(decimal_places=1, max_digits=3)),
                ('g3', models.DecimalField(decimal_places=1, max_digits=3)),
                ('g4', models.DecimalField(decimal_places=1, max_digits=3)),
                ('media_final', models.DecimalField(decimal_places=1, max_digits=3)),
                ('aluno', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siuni_site.aluno')),
                ('turma', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siuni_site.turma')),
            ],
        ),
        migrations.CreateModel(
            name='Falta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_faltas_permitidas', models.IntegerField(default=0)),
                ('total_horas_semestre', models.IntegerField(default=0)),
                ('horas_faltadas', models.IntegerField(default=0)),
                ('aluno', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siuni_site.aluno')),
                ('turma', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siuni_site.turma')),
            ],
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siuni_site.turma'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='turmas',
            field=models.ManyToManyField(blank=True, to='siuni_site.turma'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aluno', to='siuni_site.usuario'),
        ),
    ]
