# Generated by Django 4.2.16 on 2024-10-16 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siuni_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SituacaoAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nPerido', models.IntegerField(default=0)),
                ('creditos', models.IntegerField(default=0)),
                ('codCurso', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='situacao_academica',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siuni_site.situacaoacademica'),
        ),
    ]
