# Generated by Django 4.2.16 on 2024-10-19 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siuni_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siuni_site.aluno'),
        ),
    ]
