# Generated by Django 4.2.16 on 2024-10-19 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siuni_site', '0002_alter_nota_aluno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='falta',
            old_name='total_faltas_permitidas',
            new_name='total_horas_permitidas',
        ),
    ]
