# Generated by Django 4.2.16 on 2024-10-19 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siuni_site', '0005_alter_falta_turma'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='falta',
            unique_together={('aluno', 'turma')},
        ),
    ]
