# Generated by Django 4.2.16 on 2024-10-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siuni_site', '0010_alter_falta_total_horas_permitidas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='matricula',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.IntegerField(default=0),
        ),
    ]
